
jobs:
  tdd-assignment:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/testing/node_modules
          app-dir: ~/testing
          override-ci-command: npm install
      - run: 
          command: npm start
          working_directory: ~/testing
          background: true
      - run:
          command: npx mocha server.test.js
          working_directory: ~/testing
workflows:
  assignments:
    jobs:
      - tdd-assignment