version: 2.1
orbs:
  node: circleci/node@4.1.0
jobs:
  build:
    executor: 
      name: node/default
      tag: '14.5'
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/project/testing/node_modules
          app-dir: ~/project/testing
          override-ci-command: npm install
      - run: 
          command: npm start
          working_directory: ~/project/testing
          background: true
      - run:
          sleep 5
      - run:
          command: npx mocha server.test.js
          working_directory: ~/project/testing
workflows:
  testing:
    jobs:
      - build