obs:
  test:
    executor:
      name: node/default
      tag: '13.14'
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run test
orbs:
  node: circleci/node@1.1.0
version: 2.1
workflows:
  test_my_app:
    jobs:
      - test